### ISSUE TITLE
Upgrade nodejs version request

### ISSUE THREAD

**Issue by qyvlik** [Acris/docker-jenkins-nodejs#1]
# Upgrade nodejs version request

Can you upgrade the nodejs  version to v10.8.0?

**Comment by Acris** [comment]
Sure, upgraded.
See https://hub.docker.com/r/acrisliu/jenkins-nodejs/builds/ to get build details.

**Comment by Acris** [comment]
I've fixed a build issue, now you can run your container with `acrisliu/jenkins-nodejs` to use the latest version of Node.JS and Jenkins, or `acrisliu/jenkins-nodejs:lts` to use LTS version.
